language: android

jdk:
  # Jdk version used by your project
  - oraclejdk11

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    - tools
    - platform-tools
    - tools

    # The SDK version used to compile your project
    - android-31

    # Additional components
    - extra-google-google_play_services
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-31

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew clean build
  - ./gradlew test
