name: unit_tests

on:
  pull_request:
    branches:
    - 'master'
    - 'develop'

jobs:
  Unit-test:
  name: Run unit tests on PR in master and develop
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: {java-version: 11}
    - name: Run unit tests
      run: ./gradlew test